### ISSUE TITLE
logos

### ISSUE THREAD

**Issue by bhtz** [bhtz/logos#1]
My favorites are : 7, 5 and 8 !

**Comment by aZerato** [comment]
1, 4, 7 !

**Comment by antho227** [comment]
4, 5, 7

**Comment by ghost** [comment]
1, 7, 9

**Comment by cireme** [comment]
8, 5, 10

**Comment by loloakira** [comment]
5, 8, 10 et en tout cas SURTOUT PAS 2, 6, 12, 14, 15

**Comment by cireme** [comment]
je savais que tu avais du goût lolo

**Comment by aZerato** [comment]
## Recap

1 : 2
4 : 2
5 : 4
7 : 4
8 : 3
9 : 1
10 : 2

**Comment by loloakira** [comment]
Et donc quoi tout le monde a voté là ? C'est quoi cette communauté de noobs. Invite moi plus de votants là Ben ...

**Comment by cireme** [comment]
ouai, peut être réduire la taille du png, ça m'a fait freeze le navigateur et impossible de l'afficher sur mobile

**Comment by Authfix** [comment]
5, 7, 8

**Comment by bhtz** [comment]
@cireme yes pour le png je vais voir ca ! c'est cool pour les logos y'en a quelque uns qui se démarque bien.

**Comment by bhtz** [comment]
@loloakira c'est ouvert a tout le monde !

**Comment by loloakira** [comment]
Je l'ai reçu le mail qui disait "c'est ouvrir à tout le monde" oui oui je l'ai vue cette horrible faute ...

**Comment by tomadj** [comment]
7, 8 , 13
