### ISSUE TITLE
logos #2

### ISSUE THREAD

**Issue by bhtz** [bhtz/logos#3]
Un nouveau vote avec les 3 logos les plus liker ! Cette fois on n'en prend 1 !!

**Comment by bhtz** [comment]
Persos c'est 2 (ancien 7) ! J'aime bien il se démarque.

**Comment by loloakira** [comment]
Je vais aller sur 3 moi.

**Comment by tomadj** [comment]
2 aussi !!

**Comment by bhtz** [comment]
le 3 j'aime bien aussi mais il me fait trop penser a angular pour le coup

**Comment by antho227** [comment]
2

**Comment by cireme** [comment]
1

**Comment by aZerato** [comment]
2

**Comment by KromeFR** [comment]
Plutôt le 2 pour ma part.

**Comment by bhtz** [comment]
D'avis général le 2 semble remporter le concours ^^ ! Cool

**Comment by msaussac** [comment]
2

**Comment by bhtz** [comment]
On sélectionne le 2 donc ! Les déclinaisons pour microscope-ws et microscope-console vont suivre assez rapidement.
